server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Serve static files from here
    root   /usr/share/nginx/html;
    index  index.html;

    # Important for Single Page Applications (SPA)
    # Redirect all 404 access to the index.html so React Router takes over.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Cache static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
